//mutations
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCT_DETAILS = "UPDATE_PRODUCT_DETAILS";
export const UPDATE_PEODUCT_IMG_URL = "UPDATE_PEODUCT_IMG_URL";

//actions
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";

//getters
export const IMAGE_CONVERSION = "IMAGE_CONVERSION";
export const BYTE_TO_IMAGE = "BYTE_TO_IMAGE";
