//mutations
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCT_DETAILS = "UPDATE_PRODUCT_DETAILS";
export const UPDATE_PEODUCT_IMG_URL = "UPDATE_PEODUCT_IMG_URL";
export const SET_USER = "SET_USER";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";

//actions
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//getters
export const IMAGE_CONVERSION = "IMAGE_CONVERSION";
export const BYTE_TO_IMAGE = "BYTE_TO_IMAGE";
export const CURRENT_USER = "CURRENT_USER";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
